Fixing signing bugs, add misbehaviour reported
webb-tools/dkg-substrate pull request #164
Opened 2022-02-14 21:08 UTC by drewstone

**Summary of changes**
Changes introduced in this pull request:
- Adds some updates to the signing flow
- Adds reputation to the metadata pallet for offense reporting
- Adds reputation as a parameter to signer set selection

**Reference issue to close (if applicable)**

Closes

2022-02-14 22:07 UTC, dutterbutter requested changes

2022-02-14 22:07 UTC, dutterbutter commented on pallets/dkg-proposal-handler/src/lib.rs
> +	ProposalKind, ProposalNonce, TransactionV2,
I don't see `Address`, `ProposalNonce`, `ProposalHeader`, and `TransactionV2` being used, I think they can be removed.

2022-02-14 22:07 UTC, dutterbutter commented on pallets/dkg-proposal-handler/src/tests.rs
> +	EIP2930Transaction, OffchainSignedProposals, Proposal, ProposalAction, ProposalHandlerTrait,
I don't see `ProposalHandlerTrait` being used. I think it can be removed.

2022-02-16 19:05 UTC, shekohex approved these changes

2022-02-16 19:07 UTC, merged