[TASK] Add logging to see the signing process in action.
webb-tools/dkg-substrate pull request #173
Opened 2022-02-17 11:45 UTC by dharjeezy

Add logging to see the signing process in action according to #89

2022-02-17 17:19 UTC, appcypher requested changes

2022-02-17 17:19 UTC, appcypher commented on dkg-gadget/src/worker.rs
> +		let mut current_authority_id= None;
Can you format the code?

2022-02-17 17:19 UTC, appcypher commented on dkg-gadget/src/worker.rs
> +						);
Same here

2022-02-17 17:19 UTC, appcypher commented on dkg-gadget/src/worker.rs
> +				current_authority_id = Some(id.clone());
Should be able to clone `id` once here

2022-02-17 19:28 UTC, appcypher approved these changes

2022-02-21 14:38 UTC, drewstone reviewed
We're already logging the pubkeys in the pallets. We can close this.

2022-02-21 14:38 UTC, closed without merging