Keygen refresh integration tests
webb-tools/dkg-substrate pull request #26
Opened 2021-12-07 21:07 UTC by Wizdave97

2021-12-17 17:58 UTC, drewstone requested changes

2021-12-17 17:58 UTC, drewstone commented on dkg-test-suite/src/utils.ts
> +export const wait_n_finalized_blocks = async function (api: ApiPromise, n: number, timeout:  number) {
We should use camelCase for TS

2021-12-17 17:58 UTC, drewstone commented on dkg-test-suite/src/key_refresh.ts
> +
too many new lines, condense this a bit if you can.

2021-12-18 01:24 UTC, Wizdave97 commented
The master branch of substrate has been updated and the Default trait has been removed from the AccountId,  The only pallet left to be fixed is the parachain staking pallet, I'll fix that over the weekend, the tests are and bug fixes are done for the refresh though.

2021-12-19 22:57 UTC, merged