Use sr25519 to sign extrinsics
webb-tools/dkg-substrate pull request #27
Opened 2021-12-09 18:30 UTC by Wizdave97

2021-12-09 20:58 UTC, drewstone requested changes

2021-12-09 20:58 UTC, drewstone commented on pallets/dkg-metadata/src/lib.rs
> +			if recovered_pub_key != stored_key[1..].to_vec() {
Can you add docs to this? Why index at 1?

2021-12-09 22:10 UTC, drewstone requested changes

2021-12-09 23:07 UTC, Wizdave97 commented
There's only on issue left here that I'm still debugging, when the refresh voting starts, it does not progress, so it's never completed, once that is fixed, this would be ready to go.

2021-12-10 09:29 UTC, Wizdave97 commented
> There's only on issue left here that I'm still debugging, when the refresh voting starts, it does not progress, so it's never completed, once that is fixed, this would be ready to go.

Fixed up

2021-12-10 09:33 UTC, Wizdave97 commented
https://user-images.githubusercontent.com/31099392/145551452-1c883e70-103e-4ca0-b2c5-b2946cd51240.mp4

2021-12-10 13:52 UTC, shekohex approved these changes

2021-12-10 13:54 UTC, merged