Persistent DKG Restarts (WIP)
webb-tools/dkg-substrate pull request #45
Opened 2021-12-24 17:54 UTC by Wizdave97

2021-12-29 22:17 UTC, drewstone commented
Merge conflicts from latest merge @Wizdave97 here now.

2021-12-31 19:00 UTC, drewstone requested changes
Looks good! Would like more docs on how this is being tested and how you've tested this so far? Have you done a live test with nodes falling off during keygen?

2022-01-03 09:29 UTC, Wizdave97 commented
> Looks good! Would like more docs on how this is being tested and how you've tested this so far? Have you done a live test with nodes falling off during keygen?

I've tested this with three live nodes 

The tests I've run is with a node joining the keygen late when it cannot receive all the messages sent by other peers anymore.
Also tested when a node drops off before the keygen completes.

2022-01-03 15:02 UTC, temld4 approved these changes

2022-01-03 15:28 UTC, merged