Remove all ensure_root and replace with EnsureOrigin<> #2
webb-tools/dkg-substrate pull request #455
Opened 2022-11-26 23:13 UTC by herou

**Summary of changes**
Changes introduced in this pull request:
- Replace ensure_root with ensure_origin 

**Reference issue to close (if applicable)**

https://github.com/webb-tools/dkg-substrate/issues/441

2022-11-30 09:15 UTC, herou commented
@dutterbutter @drewstone Can you please review this?

2022-11-30 18:46 UTC, drewstone commented
Can you fix the lint?

2022-11-30 18:48 UTC, drewstone commented
Also why are the types all called AssetModifierOrigin when some pallets have nothing to do with assets?

2022-11-30 18:48 UTC, drewstone requested changes

2022-11-30 18:48 UTC, drewstone commented on pallets/dkg-metadata/src/lib.rs
> +		type AssetModifierOrigin: EnsureOrigin<Self::RuntimeOrigin>;
I do not agree with the naming convention used.

2022-11-30 18:48 UTC, drewstone commented on pallets/dkg-metadata/src/lib.rs
> +		type AssetModifierOrigin: EnsureOrigin<Self::RuntimeOrigin>;
Needs to be relevant for each pallet.

2022-12-16 19:21 UTC, drewstone commented
Is this still active @herou? I will close next week without comment.

2022-12-26 23:12 UTC, drewstone commented
Closing this since it's gone inactive.

2023-01-09 18:50 UTC, drewstone commented
Reopened @herou

2023-01-23 19:05 UTC, closed without merging